apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: multi-worker
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 3
      template:
        spec:
          containers:
            - name: tensorflow
              image: gcr.io/${PROJECT_ID}/${IMAGE_NAME}
              args:
                - --epochs=5
                - --steps_per_epoch=100
                - --per_worker_batch=64
                - --saved_model_path=gs://qwiklabs-gcp-02-c18a3a9ce4a1-bucket/saved_model_dir
                - --checkpoint_path=gs://qwiklabs-gcp-02-c18a3a9ce4a1-bucket/checkpoints
